// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkryefyueevnxpypzguh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrcnllZnl1ZWV2bnhweXB6Z3VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMDQ5MzAsImV4cCI6MjA2MTU4MDkzMH0.TKFMjC7sDOvEv4qZw7PBuS1pU-izPcQs4oDV3HQvEm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);